name: Build and Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

env:
  DOTNET_VERSION: "9.0"

jobs:
  calculate-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.ver.outputs.value }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get version information
        id: ver
        shell: bash
        run: |
          version="$(git describe --long --abbrev=7 2>/dev/null | sed 's/^v//;s/\([^-]*-g\)/r\1/;s/-/./g' || git rev-parse --short HEAD)"
          echo Version: $version
          echo "value=$version" >> "$GITHUB_OUTPUT"

  build-windows:
    needs: calculate-version
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v5
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.1
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "${{ env.DOTNET_VERSION }}.x"

      - name: Download dependencies
        shell: pwsh
        run: |
          $url = "https://files.catbox.moe/k555t7.zip"
          $zip = "$env:RUNNER_TEMP/mizuki-deps.zip"
          $lib = "Mizuki/lib"
          New-Item -ItemType Directory -Path $lib -Force | Out-Null
          Invoke-WebRequest -Uri $url -OutFile $zip
          Expand-Archive -Path $zip -Destinationpath $lib -Force

      - name: Build Mizuki
        shell: pwsh
        run: |
          pushd Mizuki
          zig build --release=safe
          popd

      - name: Build and Test Ameko
        shell: pwsh
        run: |
          dotnet build
          cp "Mizuki/zig-out/bin/mizuki.dll" "Tests/Holo.Tests/bin/Debug/net${{ env.DOTNET_VERSION }}/"
          cp -Force "Mizuki/lib/*" "Tests/Holo.Tests/bin/Debug/net${{ env.DOTNET_VERSION }}/"
          dotnet test

      - name: Publish Ameko
        shell: pwsh
        run: |
          pushd Ameko
          dotnet publish -c Release -p:SolutionDir=..\ -r win-x64 --self-contained true /p:PublishSingleFile=true /p:IncludeNativeLibrariesInSingleFile=true
          popd
          cp "Mizuki/zig-out/bin/mizuki.dll" "Ameko/bin/Release/net${{ env.DOTNET_VERSION }}/win-x64/publish"
          cp -Force "Mizuki/lib/*" "Ameko/bin/Release/net${{ env.DOTNET_VERSION }}/win-x64/publish/"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ameko-win-x64-${{ needs.calculate-version.outputs.version }}
          path: Ameko/bin/Release/net${{ env.DOTNET_VERSION }}/win-x64/publish

  build-macos:
    needs: calculate-version
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v5
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.1
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "${{ env.DOTNET_VERSION }}.x"

      - name: Install dependencies
        shell: bash
        run: |
          brew update
          brew install libass ffms2

      - name: Build Mizuki
        shell: bash
        run: |
          pushd Mizuki
          zig build --release=safe
          popd

      - name: Build and Test Ameko
        shell: bash
        run: |
          dotnet build
          cp "Mizuki/zig-out/lib/libmizuki.dylib" "Tests/Holo.Tests/bin/Debug/net${{ env.DOTNET_VERSION }}/"
          dotnet test

      - name: Publish Ameko
        shell: bash
        run: |
          pushd Ameko
          dotnet publish -c Release -p:SolutionDir=../ -r osx-arm64 --self-contained true /p:PublishSingleFile=true /p:IncludeNativeLibrariesInSingleFile=true
          popd
          cp "Mizuki/zig-out/lib/libmizuki.dylib" "Ameko/bin/Release/net${{ env.DOTNET_VERSION }}/osx-arm64/publish"
          echo "You will need to install libass and ffms2 to run Ameko. Example: brew install libass ffms2" > "Ameko/bin/Release/net${{ env.DOTNET_VERSION }}/osx-arm64/publish/DEPENDENCIES.txt"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ameko-mac-arm64-${{ needs.calculate-version.outputs.version }}
          path: Ameko/bin/Release/net${{ env.DOTNET_VERSION }}/osx-arm64/publish

  build-linux:
    needs: calculate-version
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.1
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "${{ env.DOTNET_VERSION }}.x"

      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libass-dev \
            libffms2-dev

      - name: Build Mizuki
        shell: bash
        run: |
          pushd Mizuki
          zig build --release=safe
          popd

      - name: Build and Test Ameko
        shell: bash
        run: |
          dotnet build
          cp "Mizuki/zig-out/lib/libmizuki.so" "Tests/Holo.Tests/bin/Debug/net${{ env.DOTNET_VERSION }}/"
          dotnet test

      - name: Publish Ameko
        shell: bash
        run: |
          pushd Ameko
          dotnet publish -c Release -p:SolutionDir=../ -r linux-x64 --self-contained true /p:PublishSingleFile=true /p:IncludeNativeLibrariesInSingleFile=true
          popd
          cp "Mizuki/zig-out/lib/libmizuki.so" "Ameko/bin/Release/net${{ env.DOTNET_VERSION }}/linux-x64/publish"
          echo "You will need to install libass and ffms2 to run Ameko. Example: sudo apt install libass ffms2" > "Ameko/bin/Release/net${{ env.DOTNET_VERSION }}/linux-x64/publish/DEPENDENCIES.txt"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ameko-linux-x64-${{ needs.calculate-version.outputs.version }}
          path: Ameko/bin/Release/net${{ env.DOTNET_VERSION }}/linux-x64/publish
