name: Build and Test
on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '0 8 * * *'

jobs:
  should-build:
    runs-on: ubuntu-latest
    outputs:
      should_build: ${{ steps.check.outputs.should_build }}
      version: ${{ steps.ver.outputs.value }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get version information
        id: ver
        shell: bash
        run: |
          version="$(git describe --long --abbrev=7 2>/dev/null | sed 's/^v//;s/\([^-]*-g\)/r\1/;s/-/./g' || git rev-parse --short HEAD)"
          echo Version: $version
          echo "value=$version" >> "$GITHUB_OUTPUT"

      - name: Check if build should be performed
        id: check
        shell: bash
        run: |
          echo "Event type: ${{ github.event_name }}"
          if [ "${{ github.event_name }}" = "schedule" ]; then
            echo "Checking for commits in the past 24 hours..."
            commits=$(git log --oneline --since='24 hours ago' | wc -l)
            echo "Commits in the last 24 hours: $commits"

            if [ "$commits" -eq 0 ]; then
              echo "No commits in the last 24 hours. Skipping workflow."
              echo "should_build=false" >> "$GITHUB_OUTPUT"
              exit 0
            fi
          fi

          echo "should_build=true" >> "$GITHUB_OUTPUT"

  build-windows:
    needs: should-build
    if: needs.should-build.outputs.should_build == 'true'
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v5
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.1
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "9.0.x"

      - name: Download dependencies
        shell: pwsh
        run: |
          $url = "https://files.catbox.moe/k555t7.zip"
          $zip = "$env:RUNNER_TEMP/mizuki-deps.zip"
          $lib = "Mizuki/lib"
          New-Item -ItemType Directory -Path $lib -Force | Out-Null
          Invoke-WebRequest -Uri $url -OutFile $zip
          Expand-Archive -Path $zip -Destinationpath $lib -Force

      - name: Build Mizuki
        shell: pwsh
        run: |
          pushd Mizuki
          zig build --release=safe
          popd

      - name: Build Ameko
        shell: pwsh
        run: |
          pushd Ameko
          dotnet publish -c Release -p:SolutionDir=..\ -r win-x64 --self-contained true /p:PublishSingleFile=true /p:IncludeNativeLibrariesInSingleFile=true
          popd

      - name: Test Ameko
        shell: pwsh
        run: dotnet test

      - name: Copy Dependencies
        shell: pwsh
        run: |
          cp "Mizuki/zig-out/bin/mizuki.dll" "Ameko/bin/Release/net9.0/win-x64/publish"
          cp -Force "Mizuki/lib/*" "Ameko/bin/Release/net9.0/win-x64/publish/"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ameko-win-x64-${{ needs.should-build.outputs.version }}
          path: Ameko/bin/Release/net9.0/win-x64/publish

  build-macos:
    needs: should-build
    if: needs.should-build.outputs.should_build == 'true'
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v5
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.1
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "9.0.x"

      - name: Cache Homebrew
        uses: actions/cache@v3
        with:
          path: |
            /opt/homebrew/Cellar
            /opt/homebrew/Cache
            /opt/homebrew/lib/
          key: ${{ runner.os }}-homebrew-deps-v1
          restore-keys: |
            ${{ runner.os }}-homebrew-deps-

      - name: Install dependencies
        shell: bash
        run: |
          brew update
          brew install libass ffms2
          brew link libass
          brew link ffms2

      - name: Build Mizuki
        shell: bash
        run: |
          pushd Mizuki
          zig build --release=safe
          popd

      - name: Build Ameko
        shell: bash
        run: |
          pushd Ameko
          dotnet publish -c Release -p:SolutionDir=../ -r osx-arm64 --self-contained true /p:PublishSingleFile=true /p:IncludeNativeLibrariesInSingleFile=true
          popd

      - name: Test Ameko
        shell: bash
        run: dotnet test

      - name: Copy Dependencies
        shell: bash
        run: |
          cp "Mizuki/zig-out/lib/libmizuki.dylib" "Ameko/bin/Release/net9.0/osx-arm64/publish"
          echo "You will need to install libass and ffms2 to run Ameko. Example: brew install libass ffms2" > "Ameko/bin/Release/net9.0/osx-arm64/publish/DEPENDENCIES.txt"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ameko-mac-arm64-${{ needs.should-build.outputs.version }}
          path: Ameko/bin/Release/net9.0/osx-arm64/publish

  build-linux:
    needs: should-build
    if: needs.should-build.outputs.should_build == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.1
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "9.0.x"

      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libass-dev \
            libffms2-dev

      - name: Build Mizuki
        shell: bash
        run: |
          pushd Mizuki
          zig build --release=safe
          popd

      - name: Build Ameko
        shell: bash
        run: |
          pushd Ameko
          dotnet publish -c Release -p:SolutionDir=../ -r linux-x64 --self-contained true /p:PublishSingleFile=true /p:IncludeNativeLibrariesInSingleFile=true
          popd

      - name: Test Ameko
        shell: bash
        run: dotnet test

      - name: Copy Dependencies
        shell: bash
        run: |
          cp "Mizuki/zig-out/lib/libmizuki.so" "Ameko/bin/Release/net9.0/linux-x64/publish"
          echo "You will need to install libass and ffms2 to run Ameko. Example: sudo apt install libass ffms2" > "Ameko/bin/Release/net9.0/linux-x64/publish/DEPENDENCIES.txt"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ameko-linux-x64-${{ needs.should-build.outputs.version }}
          path: Ameko/bin/Release/net9.0/linux-x64/publish
